export const EMAIL_REGEX = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
export const LOWER_CASE_REGEX = /([a-z]+)/;
export const UPPER_CASE_REGEX = /([A-Z]+)/;
export const PHONE_REGEX = /^(\+4|)?(07[0-8]{1}[0-9]{1}|02[0-9]{2}|03[0-9]{2}){1}?(\s|\.|\-)?([0-9]{3}(\s|\.|\-|)){2}$/;
export const COUNTRIES = [
    'Afganisztán', 
    'Albánia', 
    'Algéria', 
    'Amerikai Egyesült Államok', 
    'Andorra', 
    'Angola', 
    'Antigua és Barbuda', 
    'Argentína', 
    'Ausztrália', 
    'Ausztria', 
    'Azerbajdzsán', 
    'Bahama-szigetek', 
    'Bahrein', 
    'Banglades', 
    'Barbados', 
    'Belgium', 
    'Belize', 
    'Benin', 
    'Bosznia-Hercegovina', 
    'Bhután', 
    'Bissau-Guinea', 
    'Brunei', 
    'Bolívia', 
    'Botswana', 
    'Brazília', 
    'Bulgária', 
    'Burkina Faso', 
    'Burundi', 
    'Chile', 
    'Ciprus', 
    'Comore-szigetek', 
    'Costa Rica', 
    'Csád', 
    'Csehország', 
    'Dánia', 
    'Dél-afrikai Köztársaság', 
    'Dél-Korea', 
    'Dominikai Közösség', 
    'Dominikai Köztársaság', 
    'Dél-Szudán', 
    'Dzsibuti', 
    'Ecuador', 
    'Egyenlítői-Guinea', 
    'Egyesült Arab Emírségek', 
    'Egyesült Királyság', 
    'Egyiptom', 
    'Elefántcsontpart', 
    'Eritrea', 
    'Észak-Korea', 
    'Észak-Macedónia', 
    'Észtország', 
    'Etiópia', 
    'Fehéroroszország', 
    'Fidzsi-szigetek', 
    'Finnország', 
    'Franciaország', 
    'Fülöp-szigetek', 
    'Gabon', 
    'Gambia', 
    'Ghána', 
    'Görögország', 
    'Grenada', 
    'Grúzia', 
    'Guatemala', 
    'Guinea', 
    'Guyana', 
    'Haiti', 
    'Hollandia', 
    'Honduras', 
    'Horvátország', 
    'India', 
    'Indonézia', 
    'Irak', 
    'Irán', 
    'Írország', 
    'Izland', 
    'Izrael', 
    'Jamaica', 
    'Japán', 
    'Jemen', 
    'Jordánia', 
    'Kambodzsa', 
    'Kamerun', 
    'Kanada', 
    'Katar', 
    'Kazahsztán', 
    'Kelet-Timor', 
    'Kenya', 
    'Kína', 
    'Kirgizisztán', 
    'Kiribati', 
    'Kolumbia', 
    'Kongói Köztársaság', 
    'Kongói Demokratikus Köztársaság', 
    'Közép-afrikai Köztársaság', 
    'Kuba', 
    'Kuvait', 
    'Laosz', 
    'Lengyelország', 
    'Lesotho', 
    'Lettország', 
    'Libanon', 
    'Libéria', 
    'Líbia', 
    'Liechtenstein', 
    'Litvánia', 
    'Luxemburg', 
    'Macedónia', 
    'Madagaszkár', 
    'Magyarország', 
    'Malajzia', 
    'Malawi', 
    'Maldív-szigetek', 
    'Mali', 
    'Málta', 
    'Marokkó', 
    'Marshall-szigetek', 
    'Mauritánia', 
    'Mauritius', 
    'Mexikó', 
    'Mianmar', 
    'Mikronézia', 
    'Moldova', 
    'Monaco', 
    'Mongólia', 
    'Montenegró', 
    'Mozambik', 
    'Namíbia', 
    'Nauru', 
    'Németország', 
    'Nepál', 
    'Nicaragua', 
    'Niger', 
    'Nigéria', 
    'Norvégia', 
    'Olaszország', 
    'Omán', 
    'Oroszország', 
    'Örményország', 
    'Pakisztán', 
    'Palau', 
    'Panama', 
    'Pápua Új-Guinea', 
    'Paraguay', 
    'Peru', 
    'Portugália', 
    'Románia', 
    'Ruanda', 
    'Saint Kitts és Nevis', 
    'Saint Lucia', 
    'Saint Vincent és a Grenadine-szigetek', 
    'Salamon-szigetek', 
    'Salvador', 
    'San Marino', 
    'São Tomé és Príncipe', 
    'Seychelle-szigetek', 
    'Sierra Leone', 
    'Spanyolország', 
    'Srí Lanka', 
    'Suriname', 
    'Svájc', 
    'Svédország', 
    'Szamoa', 
    'Szaúd-Arábia', 
    'Szenegál', 
    'Szerbia', 
    'Szingapúr', 
    'Szíria', 
    'Szlovákia', 
    'Szlovénia', 
    'Szomália', 
    'Szudán', 
    'Szváziföld', 
    'Tádzsikisztán', 
    'Tanzánia', 
    'Thaiföld', 
    'Togo', 
    'Tonga', 
    'Törökország', 
    'Trinidad és Tobago', 
    'Tunézia', 
    'Tuvalu', 
    'Türkmenisztán', 
    'Uganda', 
    'Új-Zéland', 
    'Ukrajna', 
    'Uruguay', 
    'Üzbegisztán', 
    'Vanuatu', 
    'Vatikán', 
    'Venezuela', 
    'Vietnám', 
    'Zambia', 
    'Zimbabwe', 
    'Zöld-foki Köztársaság'
]