export interface Pub {
    uid: string,
    imageSrc1,
    imageSrc2,
    imageSrc3,
    companyName: string,
    country: string,
    contry: string,
    city: string,
    address: string,
    description: string,
    space: number,
    openStateMonday: boolean,
    openStateTuesday: boolean,
    openStateWednesday: boolean,
    openStateThursday: boolean,
    openStateFriday: boolean,
    openStateSaturday: boolean,
    openStateSunday: boolean,
    startingHourMonday: string,
    startingHourTuesday: string,
    startingHourWednesday: string,
    startingHourThursday: string,
    startingHourFriday: string,
    startingHourSaturday: string,
    startingHourSunday: string,
    endingHourMonday: string,
    endingHourTuesday: string,
    endingHourWednesday: string,
    endingHourThursday: string,
    endingHourFriday: string,
    endingHourSaturday: string,
    endingHourSunday: string,
    currentSpace: number,
}

export interface Pubs extends Array<Pub> {

}